BitirmeProjesi/BitirmeProjesi/Controllers/FirmaController.cs
using BitirmeProjesi.DataContext;
using BitirmeProjesi.Models.ViewModel;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;

namespace BitirmeProjesi.Controllers
{
	public class FirmaController : Controller
	{
		private readonly BitirmeProjesiDbContext DbContext;

		public FirmaController(BitirmeProjesiDbContext DbContext)
		{
			this.DbContext = DbContext;
		}


        [HttpGet]
        [Authorize(Roles = "Admin,Muhasebeci")]
        public IActionResult FirmaKayıt()
		{
            return View();
		}

		[HttpGet]
        [Authorize(Roles = "Admin,Muhasebeci")]
        public async Task<IActionResult> FirmaListeleme()
		{
			var firmalar = await DbContext.Firmalar.ToListAsync();

			return View(firmalar);


		}

       
        [HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci")]

        public async Task<IActionResult> FirmaKayıt(Firma addFirmaRequest)
		{
            if (!ModelState.IsValid)
            {
                // Masraflar property'sine ait doğrulama hatalarını kaldır
                ModelState.Remove("Masraflar");

                // Tekrar kontrol et
                if (!ModelState.IsValid)
                {
                    return View(addFirmaRequest);
                }
            }

            var firma = new Firma()
            {
                Id = Guid.NewGuid(),
                FirmaAdı = addFirmaRequest.FirmaAdı,
                TelofonNo = addFirmaRequest.TelofonNo,
                Iban = addFirmaRequest.Iban,
                İlgiliKisi = addFirmaRequest.İlgiliKisi,
                //Masraflar = new List<Masraf>() // Varsayılan olarak boş koleksiyon
            };

            DbContext.Firmalar.Add(firma);
            await DbContext.SaveChangesAsync();

            return RedirectToAction("FirmaListeleme");
        }

	

		[HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci")]
        public async Task<IActionResult> Delete(Firma updateFirma)
		{
            var firma = await DbContext.Firmalar.FindAsync(updateFirma.Id);
            if (firma == null)
            {
                return NotFound();
            }

            DbContext.Firmalar.Remove(firma);
            await DbContext.SaveChangesAsync();

            return RedirectToAction("FirmaListeleme");
        }


        [HttpGet]
        [Authorize(Roles = "Admin,Muhasebeci")]
        public async Task<IActionResult> FirmaDuzenleme(Guid id)
        {

            // Güncelleme kısmına seçtiğimiz veriyi aktardığımız kısım
            var firma = await DbContext.Firmalar.FirstOrDefaultAsync(x => x.Id == id);
            if (firma != null)
            {
                var viewModel = new Firma()
                {
                    Id = firma.Id,
                    FirmaAdı = firma.FirmaAdı,
                    TelofonNo = firma.TelofonNo,
                    Iban = firma.Iban,
                    İlgiliKisi = firma.İlgiliKisi,
                };
                return View(viewModel);
            }
            return RedirectToAction("FirmaListeleme");
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci")]
        public async Task<IActionResult> FirmaDuzenleme(Firma updateFirma)
		{

            if (!ModelState.IsValid)
            {
                // Masraflar property'sine ait doğrulama hatalarını kaldır
                ModelState.Remove("Masraflar");

                // Tekrar kontrol et
                if (!ModelState.IsValid)
                {
                    return View(updateFirma);
                }
            }

            var firma = await DbContext.Firmalar.FindAsync(updateFirma.Id);
            if (firma == null)
            {
                // Firma bulunamadıysa, hata mesajı döndürelim
                ModelState.AddModelError("", "Firma bulunamadı.");
                return View(updateFirma);
            }

            firma.FirmaAdı = updateFirma.FirmaAdı;
            firma.TelofonNo = updateFirma.TelofonNo;
            firma.Iban = updateFirma.Iban;
            firma.İlgiliKisi = updateFirma.İlgiliKisi;

            try
            {
                await DbContext.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                // Hata durumunda, ModelState'e hata ekleyelim ve kullanıcıya döndürelim
                ModelState.AddModelError("", $"Hata: {ex.Message}");
                return View(updateFirma);
            }

            return RedirectToAction("FirmaListeleme");


        }


	}
}

BitirmeProjesi/BitirmeProjesi/Controllers/GCController.cs
using BitirmeProjesi.Models.ViewModel;
using BitirmeProjesi.Models;
using ExcelDataReader;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BitirmeProjesi.DataContext;
using System.Text.RegularExpressions;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using GC = BitirmeProjesi.Models.GC;

namespace BitirmeProjesi.Controllers
{
    public class GCController : Controller
    {
        private readonly BitirmeProjesiDbContext DbContext;

        public GCController(BitirmeProjesiDbContext DbContext)
        {
            this.DbContext = DbContext;
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> GCListeleme()
        {
            var gCs = await DbContext.GCs.ToListAsync();

            return View(gCs);


        }
		[HttpPost]
		[Authorize(Roles = "Admin,Muhasebeci,Puantor")]
		public async Task<IActionResult> Delete(Guid Id)
		{
			//silme kısmı
			var gc = DbContext.GCs.Find(Id);
			if (gc != null)
			{
				DbContext.GCs.Remove(gc);
				await DbContext.SaveChangesAsync();
				return RedirectToAction("GCListeleme");
			}

			return RedirectToAction("GCListeleme");
		}
		[Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public IActionResult GCManuelKayıt()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> GCManuelKayıt(GCManuelViewModel addGCRequest)
        {
            
            if (!ModelState.IsValid)
            {
                // Masraflar property'sine ait doğrulama hatalarını kaldır
                ModelState.Remove("PersonelAd");
                ModelState.Remove("PersonelId");
                ModelState.Remove("AdSoyad");

                // Tekrar kontrol et
                if (!ModelState.IsValid)
                {
                    return View(addGCRequest);
                }
            }
            var personel = await DbContext.Personeller.FirstOrDefaultAsync(p => p.TcNo == addGCRequest.TcNo);

            if (personel == null)
            {
                ModelState.AddModelError("TCKimlikNo", "Girilen TC Kimlik Numarasına ait personel bulunamadı.");
                return View(addGCRequest);
            }
            
            //Kayıt kısmı
            var gc = new GC()
            {
                Id = Guid.NewGuid(),
                PersonelId= personel.Id,
                AdSoyad=(personel.Ad + " " + personel.Soyad),
                GS = addGCRequest.Tarih + addGCRequest.GS,
                CS = addGCRequest.Tarih + addGCRequest.CS,
                Tarih = addGCRequest.Tarih,

            };
            await DbContext.GCs.AddAsync(gc);
            await DbContext.SaveChangesAsync();

            return RedirectToAction("GCManuelKayıt");
        }

        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public IActionResult GCKayıt()
        {
            return View();
        }

        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        [HttpPost]
        public async Task<ActionResult> UploadFile(IFormFile file, GemiEnvanteriViewModel viewModel)
        {

            var personeller = await DbContext.Personeller.ToListAsync();
            string advesoyad="";

            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
            if (file != null && file.Length > 0)
            {
                var uploadDirctory = $"{Directory.GetCurrentDirectory()}\\wwwroot\\Uploads";

                if (!Directory.Exists(uploadDirctory))
                {
                    Directory.CreateDirectory(uploadDirctory);
                }
                var filePath = Path.Combine(uploadDirctory, file.Name);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                using (var stream = System.IO.File.Open(filePath, FileMode.Open, FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        while (reader.Read())
                        {

                           
                                var adsoyad = reader.GetValue(0); // adsoyad sütununun index'i
                                if (adsoyad != null) /// gelen adsoyad sutununda boş değer olmasına karşın kontrol
                                {

                                    var rowData = new Models.GC();
                                    rowData.Id = Guid.NewGuid();
                                    foreach (var item in personeller)
                                    {
                                        advesoyad = item.Ad + " " + item.Soyad;
                                        if (NormalizeString(advesoyad)==NormalizeString(adsoyad.ToString()))
                                            rowData.PersonelId = item.Id;


                                    }
                                    for (int y = 0; y < reader.FieldCount; y++)
                                    {


                                        var propertyValue = reader.GetValue(y);

                                        SetProperty(rowData, y, propertyValue); // Her sütuna karşılık gelen özelliğe veriyi ata


                                    }

                                    if (rowData.PersonelId != Guid.Empty)
                                    {
                                    //Veritabanına kaydet
                                    DbContext.GCs.Add(rowData);
                                    DbContext.SaveChanges();
                                }
                                }
                                else
                                {
                                    continue;
                                }

                           
                        }
                    }


                }

            }
            return View("GCKayıt");
        }
        public static string NormalizeString(string input)
        {
            if (input == null)
                return null;

            // Unicode normalizasyonu
            string normalized = input.Normalize(NormalizationForm.FormD);

            // Kombine edilen karakterleri kaldırma
            normalized = Regex.Replace(normalized, @"\p{Mn}", "");

            // Tüm boşlukları kaldırma
            normalized = Regex.Replace(normalized, @"\s+", "");

            // Küçük harfe çevirme
            return normalized.ToLowerInvariant();
        }
        private void SetProperty(Models.GC model, int index, object value)
        {
            switch (index)
            {
                case 0:
                    model.AdSoyad = value.ToString();
                    break;
                case 1:
                    model.Tarih = Convert.ToDateTime(value);
                    break;
                case 2:
                    model.GS = Convert.ToDateTime(value);
                    break;
                case 3:
                    model.CS = Convert.ToDateTime(value);
                    break;
                    
                default:
                    break;
            }
        }
    }
}

BitirmeProjesi/BitirmeProjesi/Controllers/GemiController.cs
using BitirmeProjesi.Models.ViewModel;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BitirmeProjesi.DataContext;
using Microsoft.AspNetCore.Authorization;

namespace BitirmeProjesi.Controllers
{
    public class GemiController : Controller
    {
        private readonly BitirmeProjesiDbContext DbContext;

        public GemiController(BitirmeProjesiDbContext DbContext)
        {
            this.DbContext = DbContext;
        }

        [Authorize(Roles = "Admin,Muhendis")]
        public IActionResult GemiKayıt()
        {
            return View();
        }


		[HttpGet]
        [Authorize(Roles = "Admin,Muhendis")]
        public async Task<IActionResult> GemiListeleme()
		{
			var gemiler = await DbContext.Gemiler.ToListAsync();

			return View(gemiler);


		}

		[HttpPost]
        [Authorize(Roles = "Admin,Muhendis")]
        public async Task<IActionResult> GemiKayıt(Gemi addGemiRequest)
        {
			if (!ModelState.IsValid)
			{
				// Masraflar property'sine ait doğrulama hatalarını kaldır
				ModelState.Remove("gemiEnvanterileri");

				// Tekrar kontrol et
				if (!ModelState.IsValid)
				{
					return View(addGemiRequest);
				}
			}
			//Kayıt kısmı
			var gemi = new Gemi()
            {
                Id = Guid.NewGuid(),
                GemiAdı = addGemiRequest.GemiAdı,
                GemiTipi = addGemiRequest.GemiTipi,
				TershaneAdı = addGemiRequest.TershaneAdı,
				TahminiBitirmeSuresi = addGemiRequest.TahminiBitirmeSuresi,
                GemiyeBaslamaTarihi = addGemiRequest.GemiyeBaslamaTarihi,

            };
            await DbContext.Gemiler.AddAsync(gemi);
            await DbContext.SaveChangesAsync();

            return RedirectToAction("GemiListeleme");
        }

		[HttpGet]
        [Authorize(Roles = "Admin,Muhendis")]
        public async Task<IActionResult> GemiDuzenleme(Guid id)
		{
			//Güncelleme kısmına seçtiğimiz veriyi aktardığımız kısım
			var gemi = await DbContext.Gemiler.FirstOrDefaultAsync(x => x.Id == id);
			if (gemi != null)
			{
				var viewModel = new Gemi()
				{
					Id = gemi.Id,
					GemiAdı = gemi.GemiAdı,
					GemiTipi= gemi.GemiTipi,
					TershaneAdı = gemi.TershaneAdı,
					TahminiBitirmeSuresi = gemi.TahminiBitirmeSuresi,
					GemiyeBaslamaTarihi = gemi.GemiyeBaslamaTarihi,
					
				};
				return await Task.Run(() => View("GemiDuzenleme", viewModel));
			}
			return RedirectToAction("PersonelListeleme");
		}

		[HttpPost]
        [Authorize(Roles = "Admin,Muhendis")]
        public async Task<IActionResult> Delete(Gemi updateGemiViewModel)
		{
			//silme kısmı
			var gemi = DbContext.Gemiler.Find(updateGemiViewModel.Id);
			if (gemi != null)
			{
				DbContext.Gemiler.Remove(gemi);
				await DbContext.SaveChangesAsync();
				return RedirectToAction("GemiListeleme");
			}

			return RedirectToAction("GemiListeleme");
		}

		[HttpPost]
        [Authorize(Roles = "Admin,Muhendis")]
        public async Task<IActionResult> GemiDuzenleme(Gemi updateGemiViewModel)
		{
			if (!ModelState.IsValid)
			{
				// Masraflar property'sine ait doğrulama hatalarını kaldır
				ModelState.Remove("gemiEnvanterileri");

				// Tekrar kontrol et
				if (!ModelState.IsValid)
				{
					return View(updateGemiViewModel);
				}
			}
			//Düzenleme yapılan kısım
			var gemi = DbContext.Gemiler.Find(updateGemiViewModel.Id);
			if (gemi != null)
			{
				gemi.GemiAdı = updateGemiViewModel.GemiAdı;
				gemi.GemiTipi = updateGemiViewModel.GemiTipi;
				gemi.TahminiBitirmeSuresi = updateGemiViewModel.TahminiBitirmeSuresi;
				gemi.GemiyeBaslamaTarihi = updateGemiViewModel.GemiyeBaslamaTarihi;
				

				await DbContext.SaveChangesAsync();

			}
			return RedirectToAction("GemiListeleme");


		}


	}
}

BitirmeProjesi/BitirmeProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BitirmeProjesi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BitirmeProjesi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">
                                        Admin Panel
                                    </a>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole("Admin") )
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Register">Hesap Açma</a>

                                        }

                                    </div>
                                </li>
                            }

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin") || User.IsInRole("Muhasebeci") || User.IsInRole("Puantor"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">
                                        Personel İşlemler
                                    </a>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole("Admin") || User.IsInRole("Muhasebeci") || User.IsInRole("Puantor"))
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Personel" asp-action="PersonelKayıt">Personel Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Personel" asp-action="PersonelListeleme">Personel Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GC" asp-action="GCKayıt">Giriş Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GC" asp-action="GCManuelKayıt">Manuel Giriş Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GC" asp-action="GCListeleme">Giriş Çıkış Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Maas" asp-action="Puantaj">Puantaj</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Maas" asp-action="MaasListeleme">Maas Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="OzelGun" asp-action="OzelGunKayıt">Özel Gün Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="OzelGun" asp-action="OzelGunListeleme">Özel Gün Listeleme</a>

                                        }

                                    </div>
                                </li>
                            }
                           
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin") || User.IsInRole("Muhasebeci"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">
                                        Finansal İşlemler
                                    </a>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole("Admin") || User.IsInRole("Muhasebeci"))
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Firma" asp-action="FirmaKayıt">Firma Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Firma" asp-action="FirmaListeleme">Firma Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Masraf" asp-action="MasrafKayıt">Masraf Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Masraf" asp-action="MasrafListeleme">Masraf Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Gelir" asp-action="GelirKayıt">Gelir Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Gelir" asp-action="GelirListeleme">Gelir Listeleme</a>
                                        }
                                    </div>
                                </li>
                            }
                           
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin") || User.IsInRole("Depocu") || User.IsInRole("Muhendis"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">
                                        Malzeme İşlemler
                                    </a>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole("Admin") || User.IsInRole("Depocu") || User.IsInRole("Muhendis"))
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Malzeme" asp-action="MalzemeKayıt">Malzeme Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Malzeme" asp-action="MalzemeListeleme">Malzeme Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Zimmet" asp-action="ZimmetKayıt">Zimmet Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Zimmet" asp-action="ZimmetListeleme">Zimmet Listeleme</a>

                                        }
                                    </div>
                                </li>
                            }
                           
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin") || User.IsInRole("Muhendis") || User.IsInRole("Muhasebeci") || User.IsInRole("Puantor"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-bs-toggle="dropdown">
                                        Gemi İşlemler
                                    </a>
                                    <div class="dropdown-menu">
                                        @if (User.IsInRole("Admin") || User.IsInRole("Muhendis"))
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Gemi" asp-action="GemiKayıt">Gemi Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Gemi" asp-action="GemiListeleme">Gemi Listeleme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GemiEnvanteri" asp-action="GemiEnvanteriKayıt">Gemi Envanteri Kayıt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GemiEnvanteri" asp-action="GemiEnvanteriSilme">Gemi Envanteri Silme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GemiSurec" asp-action="GemiSurecKayıt">Gemi Süreci Girme</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="GemiSurec" asp-action="GemiSurecListeleme">Gemi Süreci Listeleme</a>


                                        }
                                        else if (User.IsInRole("Muhasebeci") || User.IsInRole("Puantor"))
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="GemiSurec" asp-action="GemiSurecListeleme">Gemi Süreci Listeleme</a>
                                        }

                                    </div>
                                </li>
                            }
                            
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Made by erdokrmn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>