BitirmeProjesi/BitirmeProjesi/Models/Malzeme.cs
using System.ComponentModel.DataAnnotations;

namespace BitirmeProjesi.Models
{
    public class Malzeme
    {
        public Guid Id { get; set; }
		[Required(ErrorMessage = "Boş bırakmayanız .")]
		public string MalzemeAdı { get; set; }

		[Required(ErrorMessage = "Boş bırakmayanız .")]
		public string? MalzemeTürü { get; set; }

        public string? MalzemeSkt { get; set; }
		[Required(ErrorMessage = "Boş bırakmayanız .")]
		public int MalzemeAdet { get; set; }

		[Required(ErrorMessage = "Boş bırakmayanız .")]
		public int MalzemeFiyatı { get; set; }

        public string? MalzemeKodu { get; set; }
        public DateTime MalzemeAlınısTarih { get; set; }
        public bool ÜrünDurumu { get; set; }

        public ICollection<Zimmet> ZimmetEdilenMalzemeler { get; set; }

    }
}

BitirmeProjesi/BitirmeProjesi/Controllers/MalzemeController.cs
using BitirmeProjesi.Models.ViewModel;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BitirmeProjesi.DataContext;
using Microsoft.AspNetCore.Authorization;

namespace BitirmeProjesi.Controllers
{
	public class MalzemeController : Controller
	{

		private readonly BitirmeProjesiDbContext DbContext;

		public MalzemeController(BitirmeProjesiDbContext DbContext)
		{
			this.DbContext = DbContext;
		}
        [Authorize(Roles = "Admin,Muhendis,Depocu")]
        public IActionResult MalzemeKayıt()
		{
			return View();
		}
        [Authorize(Roles = "Admin,Muhendis,Depocu")]
        [HttpGet]
		public async Task<IActionResult> MalzemeListeleme()
		{
			var malzemeler = await DbContext.Malzemeler.ToListAsync();

			return View(malzemeler);


		}

        [Authorize(Roles = "Admin,Muhendis,Depocu")]
        [HttpPost]
		public async Task<IActionResult> MalzemeKayıt(Malzeme addMalzemeRequest)
		{
			if (!ModelState.IsValid)
			{
				// Masraflar property'sine ait doğrulama hatalarını kaldır
				ModelState.Remove("MalzemeTürü");
				ModelState.Remove("MalzemeKodu");
				ModelState.Remove("ZimmetEdilenMalzemeler");

				// Tekrar kontrol et
				if (!ModelState.IsValid)
				{
					return View(addMalzemeRequest);
				}
			}
			//Kayıt kısmı
			var malzeme = new Malzeme()
			{
				Id = Guid.NewGuid(),
				MalzemeAdı = addMalzemeRequest.MalzemeAdı,
				MalzemeTürü = addMalzemeRequest.MalzemeTürü,
				MalzemeSkt = addMalzemeRequest.MalzemeSkt,
				MalzemeAdet = addMalzemeRequest.MalzemeAdet,
				MalzemeFiyatı = addMalzemeRequest.MalzemeFiyatı,
				MalzemeKodu = addMalzemeRequest.MalzemeKodu,
				MalzemeAlınısTarih = addMalzemeRequest.MalzemeAlınısTarih,
				ÜrünDurumu = addMalzemeRequest.ÜrünDurumu,

			};
			await DbContext.Malzemeler.AddAsync(malzeme);
			await DbContext.SaveChangesAsync();

			return RedirectToAction("MalzemeListeleme");
		}

		[HttpGet]
        [Authorize(Roles = "Admin,Muhendis,Depocu")]
        public async Task<IActionResult> MalzemeDuzenleme(Guid id)
		{
			//Güncelleme kısmına seçtiğimiz veriyi aktardığımız kısım
			var malzeme = await DbContext.Malzemeler.FirstOrDefaultAsync(x => x.Id == id);
			if (malzeme != null)
			{
				var viewModel = new Malzeme()
				{
					Id = malzeme.Id,
					MalzemeAdı = malzeme.MalzemeAdı,
					MalzemeTürü = malzeme.MalzemeTürü,
					MalzemeSkt = malzeme.MalzemeSkt,
					MalzemeAdet = malzeme.MalzemeAdet,
					MalzemeFiyatı = malzeme.MalzemeFiyatı,
					MalzemeKodu = malzeme.MalzemeKodu,
					MalzemeAlınısTarih = malzeme.MalzemeAlınısTarih,
					ÜrünDurumu = malzeme.ÜrünDurumu,

				};
				return await Task.Run(() => View("MalzemeDuzenleme", viewModel));
			}
			return RedirectToAction("MalzemeListeleme");
		}

		[HttpPost]
        [Authorize(Roles = "Admin,Muhendis,Depocu")]
        public async Task<IActionResult> Delete(Malzeme updateMalzemeViewModel)
		{
			//silme kısmı
			var malzeme = DbContext.Malzemeler.Find(updateMalzemeViewModel.Id);
			if (malzeme != null)
			{
				DbContext.Malzemeler.Remove(malzeme);
				await DbContext.SaveChangesAsync();
				return RedirectToAction("MalzemeListeleme");
			}

			return RedirectToAction("MalzemeListeleme");
		}

		[HttpPost]
        [Authorize(Roles = "Admin,Muhendis,Depocu")]
        public async Task<IActionResult> MalzemeDuzenleme(Malzeme updateMalzemeViewModel)
		{
			if (!ModelState.IsValid)
			{
				// Masraflar property'sine ait doğrulama hatalarını kaldır
				ModelState.Remove("MalzemeTürü");
				ModelState.Remove("MalzemeKodu");
				ModelState.Remove("ZimmetEdilenMalzemeler");

				// Tekrar kontrol et
				if (!ModelState.IsValid)
				{
					return View(updateMalzemeViewModel);
				}
			}
			//Düzenleme yapılan kısım
			var malzeme = DbContext.Malzemeler.Find(updateMalzemeViewModel.Id);
			if (malzeme != null)
			{
				malzeme.MalzemeAdı = updateMalzemeViewModel.MalzemeAdı;
				malzeme.MalzemeTürü = updateMalzemeViewModel.MalzemeTürü;
				malzeme.MalzemeSkt = updateMalzemeViewModel.MalzemeSkt;
				malzeme.MalzemeAdet = updateMalzemeViewModel.MalzemeAdet;
				malzeme.MalzemeFiyatı = updateMalzemeViewModel.MalzemeFiyatı;
				malzeme.MalzemeKodu = updateMalzemeViewModel.MalzemeKodu;
				malzeme.MalzemeAlınısTarih = updateMalzemeViewModel.MalzemeAlınısTarih;
				malzeme.ÜrünDurumu = updateMalzemeViewModel.ÜrünDurumu;


				await DbContext.SaveChangesAsync();

			}
			return RedirectToAction("MalzemeListeleme");


		}
	}
}

BitirmeProjesi/BitirmeProjesi/Views/Malzeme/MalzemeDuzenleme.cshtml
@model BitirmeProjesi.Models.Malzeme


<form method="post" asp-action="MalzemeDuzenleme" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Adı</label>
        <input type="text" class="form-control" asp-for="MalzemeAdı">
        <span asp-validation-for="MalzemeAdı" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Tipi</label>
        <input type="text" class="form-control" asp-for="MalzemeTürü">
        <span asp-validation-for="MalzemeTürü" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">SKT</label>
        <input type="text" class="form-control" asp-for="MalzemeSkt">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Adet</label>
        <input type="number" class="form-control" asp-for="MalzemeAdet">
        <span asp-validation-for="MalzemeAdet" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Fiyatı</label>
        <input type="number" class="form-control" asp-for="MalzemeFiyatı">
        <span asp-validation-for="MalzemeFiyatı" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Kodu</label>
        <input type="text" class="form-control" asp-for="MalzemeKodu">
    </div>


    <div class="mb-3">
        <label for="" class="form-label">Alınış Tarihi</label>
        <input type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" asp-for="MalzemeAlınısTarih">
    </div>
      <div class="mb-3">
        <label for="" class="form-label">Ürün Durumu</label>
        <input type="checkbox" class="form-check" asp-for="ÜrünDurumu">
    </div>

    <button type="submit" class="btn btn-primary">Düzenle</button>
    <button type="submit" class="btn btn-danger"
            asp-action="Delete"
            asp-controller="Malzeme" onclick="return confirm('Bu kaydı silmek istediğinizden emin misiniz?');">
         Sil
    </button>
</form>

BitirmeProjesi/BitirmeProjesi/Views/Malzeme/MalzemeKayıt.cshtml
@model BitirmeProjesi.Models.Malzeme


<form method="post" asp-action="MalzemeKayıt" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Adı</label>
        <input type="text" class="form-control" asp-for="MalzemeAdı">
        <span asp-validation-for="MalzemeAdı" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Türü</label>
        <input type="text" class="form-control" asp-for="MalzemeTürü">
        <span asp-validation-for="MalzemeTürü" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Skt</label>
        <input type="text" class="form-control" asp-for="MalzemeSkt">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Adet</label>
        <input type="number" class="form-control" asp-for="MalzemeAdet">
        <span asp-validation-for="MalzemeAdet" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Fiyat</label>
        <input type="number" class="form-control" asp-for="MalzemeFiyatı">
        <span asp-validation-for="MalzemeFiyatı" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Malzeme Kodu</label>
        <input type="string" class="form-control" asp-for="MalzemeKodu">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Alınış Tarihi</label>
        <input type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" asp-for="MalzemeAlınısTarih">
    </div>
      <div class="mb-3">
        <label for="" class="form-label">Ürün Durumu</label>
        <input type="checkbox" class="form-inline" asp-for="ÜrünDurumu">
    </div>

    <button type="submit" class="btn btn-primary">Kayıt Et</button>
</form>

BitirmeProjesi/BitirmeProjesi/Views/Malzeme/MalzemeListeleme.cshtml
@model List<BitirmeProjesi.Models.Malzeme>

@{

}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.css">
<div class="table-responsive">
	<table id="Malzeme" class="table table-striped table-bordered dt-responsive text-nowrap overflow-scroll">
		<thead>
			<tr>
				<th>Malzeme Adı</th>
				<th>Malzeme Türü</th>
				<th>Malzeme SKT</th>
				<th>Malzeme Adet</th>
				<th>Malzeme Fiyat</th>
				<th>Malzeme Kodu</th>
				<th>Alım Tarihi</th>
				<th>Ürün Durumu</th>
				<th>Düzenleme</th>


			</tr>
		</thead>
		<tbody>
			@foreach (var malzeme in Model)
			{
					<tr>
						<td>@malzeme.MalzemeAdı</td>
						<td>@malzeme.MalzemeTürü</td>
						<td>@malzeme.MalzemeSkt</td>
						<td>@malzeme.MalzemeAdet</td>
						<td>@malzeme.MalzemeFiyatı</td>
						<td>@malzeme.MalzemeKodu</td>
						<td>@malzeme.MalzemeAlınısTarih.ToString("dd-MM-yyyy")</td>
						@if (malzeme.ÜrünDurumu == true)
					{
						<td>Kullanılabilir</td>
					}
					@if (malzeme.ÜrünDurumu == false)
					{
						<td>Kullanılıyor</td>
					}
						<td>
							<a href="MalzemeDuzenleme/@malzeme.Id">Düzenle Veya Sil</a>
						</td>
					</tr>
			}
		</tbody>
	</table>

</div>

<script src="https://code.jquery.com/jquery-3.7.1.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.js"></script>
<script>
	new DataTable('#Malzeme');
</script>