BitirmeProjesi/BitirmeProjesi/Models/OzelGun.cs
using System.ComponentModel.DataAnnotations;

namespace BitirmeProjesi.Models
{
    public class OzelGun
    {
        public Guid Id { get; set; }

       
        [Required(ErrorMessage = "Resmi Tatil adı gereklidir.")]
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
    }
}

BitirmeProjesi/BitirmeProjesi/Controllers/OzelGunController.cs
using BitirmeProjesi.DataContext;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BitirmeProjesi.Controllers
{
    public class OzelGunController : Controller
    {
        private readonly BitirmeProjesiDbContext DbContext;

        public OzelGunController(BitirmeProjesiDbContext DbContext)
        {
            this.DbContext = DbContext;
        }

        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public IActionResult OzelGunKayıt()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> OzelGunListeleme()
        {
            var ozelgunler = await DbContext.OzelGunler.ToListAsync();

            return View(ozelgunler);


        }

        [HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> OzelGunKayıt(OzelGun addOzelGunRequest)
        {
            if (!ModelState.IsValid)
            {
                return View(addOzelGunRequest);
            }
            //Kayıt kısmı
            var ozelgun = new OzelGun()
            {
                Id = Guid.NewGuid(),
                Name = addOzelGunRequest.Name,
                StartDate = addOzelGunRequest.StartDate,
                EndDate = addOzelGunRequest.EndDate,

            };
            await DbContext.OzelGunler.AddAsync(ozelgun);
            await DbContext.SaveChangesAsync();

            return RedirectToAction("OzelGunListeleme");
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> OzelGunDuzenleme(Guid id)
        {
            //Güncelleme kısmına seçtiğimiz veriyi aktardığımız kısım
            var ozelgunler = await DbContext.OzelGunler.FirstOrDefaultAsync(x => x.Id == id);
            if (ozelgunler != null)
            {
                var viewModel = new OzelGun()
                {
                    Id = ozelgunler.Id,
                    Name = ozelgunler.Name,

                    StartDate = ozelgunler.StartDate,
                    EndDate = ozelgunler.EndDate,

                };
                return await Task.Run(() => View("OzelGunDuzenleme", viewModel));
            }
            return RedirectToAction("OzelGunListeleme");
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> Delete(OzelGun updateGelirViewModel)
        {
            //silme kısmı
            var ozel = DbContext.OzelGunler.Find(updateGelirViewModel.Id);
            if (ozel != null)
            {
                DbContext.OzelGunler.Remove(ozel);
                await DbContext.SaveChangesAsync();
                return RedirectToAction("OzelGunListeleme");
            }

            return RedirectToAction("OzelGunListeleme");
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Muhasebeci,Puantor")]
        public async Task<IActionResult> OzelGunDuzenleme(OzelGun updateOzelGun)
        {
            if (!ModelState.IsValid)
            {
                return View(updateOzelGun);
            }
            //Düzenleme yapılan kısım
            var ozelgun = DbContext.OzelGunler.Find(updateOzelGun.Id);
            if (ozelgun != null)
            {
                ozelgun.Name = updateOzelGun.Name;
                ozelgun.StartDate = updateOzelGun.StartDate;
                ozelgun.EndDate = updateOzelGun.EndDate;


                await DbContext.SaveChangesAsync();

            }
            return RedirectToAction("OzelGunListeleme");


        }
    }
}

BitirmeProjesi/BitirmeProjesi/Views/OzelGun/OzelGunDuzenleme.cshtml
@model BitirmeProjesi.Models.OzelGun


<form method="post" asp-action="OzelGunDuzenleme" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Masraf Adı</label>
        <input type="text" class="form-control" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>


    <div class="mb-3">
        <label for="" class="form-label">Başlangıç Tarihi</label>
        <input type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" asp-for="StartDate">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Bitiş Tarihi</label>
        <input type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" asp-for="EndDate">
    </div>



    <button type="submit" class="btn btn-primary">Kayıt Et</button>
    <button type="submit" class="btn btn-danger"
            asp-action="Delete"
            asp-controller="OzelGun" onclick="return confirm('Bu kaydı silmek istediğinizden emin misiniz?');">
        Sil
    </button>
</form>

BitirmeProjesi/BitirmeProjesi/Views/OzelGun/OzelGunKayıt.cshtml
@model BitirmeProjesi.Models.OzelGun


<form method="post" asp-action="OzelGunKayıt" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Özel Gün Adı</label>
        <input type="text" class="form-control" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Başlangıç Tarihi</label>
        <input type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" asp-for="StartDate">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Bitiş Tarihi</label>
        <input type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control" asp-for="EndDate">
    </div>
  


    <button type="submit" class="btn btn-primary">Kayıt Et</button>
</form>

BitirmeProjesi/BitirmeProjesi/Views/OzelGun/OzelGunListeleme.cshtml
@model List<BitirmeProjesi.Models.OzelGun>

@{

}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.css">
<div class="table-responsive">
	<table id="example" class="table table-striped table-bordered dt-responsive text-nowrap overflow-scroll">
		<thead>
			<tr>
				<th>Özel Gün Adı</th>
				<th>Başlangıç Tarihi</th>
				<th>Bitiş Tarihi</th>
				<th>Düzenleme</th>
				

			</tr>
		</thead>
		<tbody>
			@foreach (var ozelgun in Model)
			{
				<tr>
					<td>@ozelgun.Name</td>

					<td>@ozelgun.StartDate.ToString("dd-MM-yyyy")</td>
					<td>@ozelgun.EndDate.ToString("dd-MM-yyyy")</td>
					<td>
						<a href="OzelGunDuzenleme/@ozelgun.Id">Düzenle Veya Sil</a>
					</td>
					
				</tr>

			}
		</tbody>
	</table>

</div>

<script src="https://code.jquery.com/jquery-3.7.1.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.js"></script>


<script>
	new DataTable('#example');

</script>